In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
%cd /content/drive/MyDrive/Colab\ Notebooks/

/content/drive/MyDrive/Colab Notebooks


In [3]:
!git clone https://github.com/egemensert/segregation.git

Cloning into 'segregation'...
remote: Enumerating objects: 38, done.
remote: Counting objects: 100% (38/38), done.
remote: Compressing objects: 100% (35/35), done.
remote: Total 38 (delta 20), reused 6 (delta 3), pack-reused 0
Unpacking objects: 100% (38/38), done.


In [4]:
!ls

 BrizaSubmit_Assignment4.ipynb		  Untitled0.ipynb
'PyTorch tutorial UCB'			  Untitled1.ipynb
 segregation				  Untitled2.ipynb
 Teaching_to_Learning_Demo_KMeans.ipynb   Untitled3.ipynb


In [5]:
%cd /content/drive/MyDrive/Colab\ Notebooks/segregation

/content/drive/MyDrive/Colab Notebooks/segregation


In [6]:
!pwd

/content/drive/MyDrive/Colab Notebooks/segregation


In [7]:
!python schelling_example.py my_experiment 10 5 75 100 1 1 1

/content/drive/MyDrive/Colab Notebooks/segregation/mind.py:142: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at  ../torch/csrc/utils/tensor_new.cpp:201.)
  batch_state = torch.cat([torch.FloatTensor(s) for s in batch_state])
SIMULATION IS FINISHED.


In [8]:
!ls

agent.py	mind.py        __pycache__  schelling_example.py
environment.py	my_experiment  README.md


In [10]:
!ls my_experiment

crystal.npy.gz	episodes


In [13]:
!cat my_experiment/episodes/a_age.csv

1, 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 0 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1, 236 200 50 67 15 107 36 111 152 80 83 92 102 174 176 204 202 228 172 87 28 40 226 13 104 134 208 63 19 224 96 89 18 182 17 157 163 218 14 245 35 215 10 86 143 159 29 136 76 137 220 158 45 181 169 46 244 54 212 71 225 66 240 149 147 144 113 105 49 1 217 187 191 131 190 3 214 156 43 78 11 234 125 94 41 27 130 221 22 103 62 122 8 189 150 72 48 231 238 75 47 164 209 74 117 197 59 237 112 222 56 210 55 232 233 5 151 242 184 68 114 178 0 241 99 213 7 124 24 97 166 30 65 195
2, 0 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 0 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 0 2 2 2 0 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 0 2 2 2 2 2 2 2 2 2 2 2 2 0 2 2 2 2 2 2 2 2 2 2 2 0 2 2 2 2 2 2 2 2 0 2 2 2 2 2 2 2 2 2 2 2 

In [14]:
!cat my_experiment/episodes/b_age.csv

1, 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1, 188 180 33 39 98 82 91 146 207 60 139 119 170 223 123 121 198 38 116 12 153 229 219 177 73 118 101 235 132 20 21 37 84 31 167 57 9 4 32 23 186 154 211 42 183 79 69 206 230 179 52 64 70 61 239 162 109 193 90 160 51 203 148 199 165 133 95 140 93 44 243 168 100 127 77 171 129 128 85 161 25 142 106 173 192 88 141 135 185 108 175 2 138 6 227 81 26 58 196 155 110 53 201 120 115 194 126 16 205 216 145 34
2, 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 0 2 2 2 2 2 0 2 2 2 2 2 2 2 2 2 2 0 2 2 2 2 2 2 2 0 2 0 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 1 0 2 2 2 2 2 2 0 2 2 2 2 2 2 2 2 2 2 2 2 2 0 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2, 243 177 161 135 196 199 70 98 183 90 58 85 52 57 12 219 115 34 93 108 193 194 127 211 77 186 100 126 2 61 6 132 188 42 82 26 119 185 173 37 116

In [15]:
!cat my_experiment/episodes/a_loss.npy

�NUMPYv{'descr': '<f8', 'fortran_order': False, 'shape': (8,), }                                                            
~�i@@�\@��9X@@��a@�0�a@@^[f@�ɖl@��@

In [20]:
import numpy as np
with open('my_experiment/episodes/a_loss.npy', 'rb') as f:
    a_loss = np.load(f)
print(len(a_loss), a_loss)      

8 [207.76538086 115.00038147  96.90457153 141.32998657 141.38095093
 178.85525513 228.71214294   3.0121913 ]


In [21]:
with open('my_experiment/episodes/b_loss.npy', 'rb') as f:
    b_loss = np.load(f)
print(len(b_loss), b_loss)    

7 [207.31005859 161.12371826  93.543396   206.91160583 139.45608521
 134.66804504 115.13879395]


In [22]:
import gzip

In [29]:
# write command
#f = gzip.GzipFile('%s/crystal.npy.gz' % self.name, "w")
#np.save(f, self.crystal)
#f.close()

The crystal is a four dimensional tensor of the simulation where the dimensions are as following: (ITERATION_INDEX, HORIZONTAL_LOCATION, VERTICAL_LOCATION, CHANNEL). 

CHANNEL = {0: agent type, 1: agent age, 2: agent id}. 

For example the slice slice = crystal[0, 5, 5, :] gives the type, age and id of the agent at location (5,5) in the first iteration. If the location is not occupied by an agent, then the slice is a zero

In [28]:
f = gzip.open('my_experiment/crystal.npy.gz','rb')
crystal = np.load(f)
type(crystal), crystal.shape  #iterations, env_x, env_y, 

(numpy.ndarray, (10, 50, 50, 4))

In [26]:
crystal

array([[[[  0.,   0.,   0.,   0.],
         [  0.,   0.,   0.,   0.],
         [  0.,   0.,   0.,   0.],
         ...,
         [  0.,   0.,   0.,   0.],
         [  0.,   0.,   0.,   0.],
         [  0.,   0.,   0.,   0.]],

        [[  0.,   0.,   0.,   0.],
         [  0.,   0.,   0.,   0.],
         [  0.,   0.,   0.,   0.],
         ...,
         [  0.,   0.,   0.,   0.],
         [  0.,   0.,   0.,   0.],
         [ -1.,   1.,  99.,  19.]],

        [[ -1.,   1.,  99.,   7.],
         [  0.,   0.,   0.,   0.],
         [  0.,   0.,   0.,   0.],
         ...,
         [  0.,   0.,   0.,   0.],
         [ -1.,   1.,  99.,  10.],
         [  0.,   0.,   0.,   0.]],

        ...,

        [[  0.,   0.,   0.,   0.],
         [  0.,   0.,   0.,   0.],
         [  0.,   0.,   0.,   0.],
         ...,
         [  0.,   0.,   0.,   0.],
         [  0.,   0.,   0.,   0.],
         [  0.,   0.,   0.,   0.]],

        [[  0.,   0.,   0.,   0.],
         [  0.,   0.,   0.,   0.],
         [  

In [33]:
# crystal[0, 5, 5, :] gives the type, age and id of the agent at location (5,5) in the first iteration
crystal[5, 5, 5, :]

array([0., 0., 0., 0.])

In [35]:
for i in range(50):
  c = crystal[5, i, 5, :]
  if c.sum() !=0:
    print(i)
    break

1


In [36]:
# agent type, age, time remaining, index
crystal[5, 1, 5, :]

array([-1.,  6., 94., 11.])

In [50]:
import time
start_time = time.time()
!python schelling_example.py exp5K 5000 5 75 100 1 1 1
seconds = round(time.time() - start_time)
print(f"---Time elapsed: {seconds/60:.2f} minutes ---")


/content/drive/MyDrive/Colab Notebooks/segregation/mind.py:142: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at  ../torch/csrc/utils/tensor_new.cpp:201.)
  batch_state = torch.cat([torch.FloatTensor(s) for s in batch_state])
SIMULATION IS FINISHED.
---Time elapsed: 35.10 minutes ---
